### ISSUE TITLE
Route To 1.0.0

### ISSUE THREAD

**Issue by AldaronLau** [ardaku/whisk#22]
- [x] Remove `Weak::try_recv()` https://github.com/ardaku/whisk/issues/23
 - [ ] Wait for pasts 1.0.0, or find a way to make backwards compatible (old pasts versions depending on new - but not exactly?)
 - [x] ~Make some functions `const`?  Like `Channel::new()` and `Weak::new()` [^1] (could be put off)~
 - [ ] Do better benchmarks https://github.com/ardaku/whisk/issues/21 (could be post 1.0.0)
 - [x] Attempt lockless waker https://github.com/ardaku/whisk/issues/18 (could be post 1.0.0)
 - [ ] https://github.com/ardaku/whisk/issues/27 (could be post 1.0.0)
 - [ ] https://github.com/ardaku/whisk/issues/31

[^1]: **Edit**: Would depend on https://github.com/rust-lang/rust/pull/95965 & https://github.com/rust-lang/rust/issues/79597
